/** Curriculum Terminal: routed technical handbook pages with folio covers, evidence bands, source classes, and dense readable records. */
import type { ReactNode } from "react";
import { AlertTriangle, ArrowUpRight, BookOpen, Check, ClipboardList, Code2, ExternalLink, FileText, Landmark, Library, ShieldAlert, UsersRound } from "lucide-react";
import { Link } from "wouter";
import { Breadcrumb, BreadcrumbItem, BreadcrumbLink, BreadcrumbList, BreadcrumbPage, BreadcrumbSeparator } from "@/components/ui/breadcrumb";
import { assets, calendarRows, communities, contacts, cseCourseNotes, departmentDirectory, extraPanels, facultyRows, feeRows, linkGroups, placementHistory, placementRows, programmingMap, recruiterAndPreparation, resourceBlocks, safeguardLinks, semOne, semTwo, sitePages, socials } from "@/data/siteData";

type PageProps = { id: typeof sitePages[number]["id"]; children: ReactNode; hero?: boolean };
type Rows = readonly (readonly string[])[];

function External({ href, children }: { href: string; children: ReactNode }) { return <a className="external-link" href={href} target="_blank" rel="noreferrer">{children}<ArrowUpRight size={14} /></a>; }
function Table({ head, rows }: { head: string[]; rows: Rows }) { return <div className="table-wrap"><table><thead><tr>{head.map((cell) => <th key={cell}>{cell}</th>)}</tr></thead><tbody>{rows.map((row, rowIndex) => <tr key={`${row[0]}${rowIndex}`}>{row.map((cell, cellIndex) => <td key={`${cell}${cellIndex}`}>{cell}</td>)}</tr>)}</tbody></table></div>; }
function Evidence({ children, label = "SOURCE NOTE" }: { children: ReactNode; label?: string }) { return <div className="evidence"><span>{label}</span><p>{children}</p></div>; }
function PageFrame({ id, children, hero = false }: PageProps) {
  const page = sitePages.find((candidate) => candidate.id === id)!;
  const coverLine: Record<typeof page.id, string> = {
    home: "Build the official route before the deadline builds pressure.",
    links: "One verified route beats ten forwarded screenshots.",
    resources: "A useful CSE stack is small, repeatable and source-aware.",
    curriculum: "Read the current document before treating a code or date as binding.",
    placements: "Quote the reporting basis. Recheck the current report.",
    faculty: "Use the right desk, with the current source, for the right question.",
    social: "Institutional channels and student community signals are not the same thing.",
    extras: "Keep a verified route for every real-world requirement.",
  };
  return <div className={`page-shell ${hero ? "home-shell" : ""}`}>
    <section className={`page-cover cover-${id}`}>
      {hero && <div className="home-visual" style={{ backgroundImage: `url(${assets.hero})` }} />}
      <div className="cover-grid" aria-hidden="true" />
      <div className="cover-copy">
        <Breadcrumb className="page-breadcrumb"><BreadcrumbList><BreadcrumbItem><BreadcrumbLink asChild><Link href="/">HOME</Link></BreadcrumbLink></BreadcrumbItem>{id !== "home" && <><BreadcrumbSeparator /><BreadcrumbItem><BreadcrumbPage>{page.label.toUpperCase()}</BreadcrumbPage></BreadcrumbItem></>}</BreadcrumbList></Breadcrumb>
        <div className="cover-meta"><span>ROUTE {page.no}</span><span>LAST RESEARCH: 27 AUG 2026</span></div>
        <h1>{page.label}</h1>
        <p>{coverLine[id]}</p>
      </div>
      <div className="cover-number" aria-hidden="true">{page.no}</div>
      <div className="route-map" aria-hidden="true"><span>↗</span><i /><b>ROUTE MAP / {page.no}</b><i /></div>
      <div className="cover-signal">AEC<i>//</i>CSE<br />CHEATSHEET</div>
    </section>
    <div className="page-content">{children}</div>
  </div>;
}

function SectionHead({ no, eyebrow, title, children }: { no: string; eyebrow: string; title: string; children?: ReactNode }) { return <div className="section-head"><span>{no}</span><div><p>{eyebrow}</p><h2>{title}</h2>{children && <div className="section-intro">{children}</div>}</div></div>; }
function RouteSummary({ title, items }: { title: string; items: readonly [string, string][] }) { return <div className="route-summary"><div className="summary-title"><span>FIELD RECORD / AT A GLANCE</span><b>{title}</b></div>{items.map(([label, value]) => <div className="summary-cell" key={label}><span>{label}</span><b>{value}</b></div>)}</div>; }
function LinkRow({ title, href, tag, note }: { title: string; href: string; tag: string; note: string }) { return <External href={href}><span className="tag">{tag}</span><span><b>{title}</b><small>{note}</small></span></External>; }

export function HomePage() { return <PageFrame id="home" hero>
  <section className="page-block home-intro"><div className="home-action"><span>FIRST 20 MINUTES</span><h2>Save the three routes that govern your academic record.</h2><ol><li><b>01</b><span><strong>AEC notices</strong> for college instructions and department context.</span></li><li><b>02</b><span><strong>MAKAUT Exam</strong> for routines, form-fill-up and university notices.</span></li><li><b>03</b><span><strong>Current syllabus index</strong> for your actual course document.</span></li></ol><Link href="/links" className="route-button">OPEN IMPORTANT LINKS <ArrowUpRight size={16} /></Link></div><div className="home-brief"><span className="datum">AEC//CSE · FIELD MANUAL / 2026</span><p>AECCHEATSHEET is a static, B.Tech CSE-first handbook. It is deliberately built around public source routes, not access to private academic systems.</p><Evidence label="HOW TO USE THIS">For deadlines, fees, attendance, exams or formal requests: open the latest official notice again, even if this guide names the route.</Evidence></div></section>
  <section className="page-block split-block"><div><SectionHead no="01" eyebrow="START WITH THE SOURCE" title="What this handbook does differently">It separates <strong>official institutional routes</strong>, public department pages, login-gated systems, search-verified candidates, and club-maintained resources.</SectionHead></div><div className="source-ladder"><p><b>01 / Binding academic action</b> Latest MAKAUT notice → current AEC circular</p><p><b>02 / Programme information</b> Current MAKAUT syllabus → AEC department page</p><p><b>03 / Fee or accommodation</b> Current AEC demand/form → college office</p><p><b>04 / Community opportunity</b> Club-maintained update → verify the event owner and deadline</p></div></section>
  <section className="page-block route-grid"><article><FileText /><span>ACADEMIC SYSTEM</span><h3>Curriculum, dates & exam checkpoints</h3><p>First-year CSE semester tables, assessment cadence, source limits and batch checks.</p><Link href="/curriculum">OPEN CURRICULUM <ArrowUpRight size={14} /></Link></article><article><Code2 /><span>LEARNING SYSTEM</span><h3>Programming & resource stack</h3><p>A practical route from C fundamentals to Git, DSA, Python and responsible tools.</p><Link href="/resources">OPEN RESOURCES <ArrowUpRight size={14} /></Link></article><article><UsersRound /><span>PEOPLE SYSTEM</span><h3>Faculty, contacts & departments</h3><p>Full public CSE faculty list, support contacts and wider department map.</p><Link href="/faculty">OPEN DIRECTORY <ArrowUpRight size={14} /></Link></article></section>
</PageFrame>; }

export function LinksPage() { return <PageFrame id="links"><section className="page-block"><SectionHead no="02.1" eyebrow="LINK DIRECTORY" title="Important links">Every gateway has a source class. “Login” and “Gateway” mean the route is public but the underlying service may require credentials or current AEC instructions.</SectionHead><RouteSummary title="18 listed student routes" items={[["SOURCE CLASSES", "4"], ["OFFICIAL-LED", "12+"], ["CREDENTIAL GATES", "4"]]} /><div className="link-groups">{linkGroups.map((group) => <section className="link-group" key={group.label}><div className="group-label"><span>{group.label}</span><p>{group.note}</p></div>{group.items.map(([title, href, tag, note]) => <LinkRow key={title} title={title} href={href} tag={tag} note={note} />)}</section>)}</div><Evidence label="ACCOUNT SAFETY"><strong>Never enter a password, OTP, registration number or fee-payment detail</strong> through a link that is not reached from an official AEC/MAKAUT page or an instruction you can verify with AEC. The public AEC navigation shows “Student Login,” but no stable, independently verified ERP explanation was found.</Evidence></section></PageFrame>; }

export function ResourcesPage() { return <PageFrame id="resources"><section className="page-block"><SectionHead no="03.1" eyebrow="STUDY SYSTEM" title="Resources that earn their place">Start with source-backed material and tools that let you produce work. Community learning links are included only where they are established, legitimate and clearly marked as non-institutional.</SectionHead><div className="resource-list">{resourceBlocks.map((block) => <article key={block.no}><div><span>{block.no}</span><p>{block.label}</p></div><div><h3>{block.title}</h3><p>{block.text}</p></div><nav>{block.links.map(([title, href]) => <External href={href} key={title}>{title}</External>)}</nav></article>)}</div></section><section className="page-block dark-record"><SectionHead no="03.2" eyebrow="CSE PRACTICE SEQUENCE" title="A workable first programming loop">The Semester II CSE course formally includes programming for problem solving and introductory AI. Use the earlier weeks to make syntax, tracing and small programs routine—not decorative.</SectionHead><Table head={["Window", "Focus", "Evidence you should create"]} rows={programmingMap} /><Evidence label="PRACTICE RULE">Copying a program is not practice. Re-type it, change one input or branch, explain the output, and commit the working version.</Evidence></section><section className="page-block"><SectionHead no="03.3" eyebrow="LIGHTWEIGHT TOOLKIT" title="Keep it simple enough to maintain"><strong>Editor:</strong> VS Code or another lightweight code editor. <strong>Version control:</strong> Git and one GitHub repository per practice track. <strong>Calculator:</strong> a scientific calculator or Desmos for checking—not replacing—steps. <strong>Study record:</strong> one file or notebook for errors you now know how to fix.</SectionHead></section></PageFrame>; }

export function CurriculumPage() { return <PageFrame id="curriculum"><section className="page-block"><SectionHead no="04.1" eyebrow="B.TECH CSE / FIRST YEAR" title="Your official curriculum map">MAKAUT’s NEP index lists B.Tech CSE, course code 001, for AY 2026–27. The linked first-year PDFs say the first year is common across B.Tech programmes and CSE is in Group A. Your own admission batch and AEC instruction still decide what applies.</SectionHead><RouteSummary title="First-year CSE baseline" items={[["SEMESTER I", "20 CREDITS"], ["SEMESTER II", "24 CREDITS"], ["TRACK", "CSE / GROUP A"]]} /><div className="batch-callout"><AlertTriangle size={20} /><div><b>BATCH CHECK</b><p>“R25” and an AY 2026–27 document are not automatically interchangeable. Confirm your applicable document with AEC before relying on codes, credits or dates.</p></div></div><div className="semester-heading"><div><span>SEMESTER I</span><h3>20 credits listed</h3></div><External href="https://makautexam.net/aicte_details/Syllabusnep/sem126.pdf">OPEN OFFICIAL PDF</External></div><Table head={["Code", "Course", "L–T–P", "Credits", "Scope"]} rows={semOne} /><p className="table-note"><Check size={16} />The linked Semester I document also states a mandatory non-credit, three-week induction programme with Universal Human Values before the semester.</p><div className="semester-heading"><div><span>SEMESTER II</span><h3>24 credits listed</h3></div><External href="https://makautexam.net/aicte_details/Syllabusnep/sem226.pdf">OPEN OFFICIAL PDF</External></div><Table head={["Code", "Course", "L–T–P", "Credits", "Scope"]} rows={semTwo} /></section><section className="page-block"><SectionHead no="04.2" eyebrow="CSE COURSE FOCUS" title="Know the modules that change your study routine" /><Table head={["Code", "Course", "Operational reading"]} rows={cseCourseNotes} /></section><section className="page-block dark-record"><SectionHead no="04.3" eyebrow="PROVISIONAL DATES" title="Assessment and exam checkpoints">This calendar is an orientation tool, not a substitute for the current MAKAUT/AEC notice. Keep your CA schedule, attendance context, form-fill-up acknowledgement and revised routine together.</SectionHead><Table head={["Period", "Odd semester 2026–27", "Even semester 2026–27"]} rows={calendarRows} /><Evidence label="EXAM CONTROL">When a date changes, save the latest official URL or PDF with the notice date—not only a screenshot shared in a group.</Evidence></section></PageFrame>; }

export function PlacementsPage() { return <PageFrame id="placements"><section className="page-block"><SectionHead no="05.1" eyebrow="EVIDENCE, NOT ADVERTISING" title="Published placement record">The table keeps each source’s reporting basis visible. A number can be accurate within its own report yet not be comparable with another source’s measure or batch stage.</SectionHead><div className="placement-warning"><AlertTriangle size={19} /><p><b>2023 conflict kept visible:</b> the WBJEEB-hosted AEC-supplied profile lists ₹23 LPA maximum CTC, while AEC’s homepage and Shiksha cite ₹22 LPA. Do not choose a convenient figure; state the source basis and open the newest AEC report.</p></div><Table head={["Year / unit", "Published count", "Published result", "Evidence / caution"]} rows={placementRows} /></section><section className="page-block"><SectionHead no="05.2" eyebrow="FIVE-YEAR RESEARCH LIMIT" title="What the public trail supports">A multi-year view exists, but a complete five-year CSE-only time series was not publicly located. The historical context below shows coverage rather than pretending the gap does not exist.</SectionHead><Table head={["Period", "Public coverage", "How to read it"]} rows={placementHistory} /></section><section className="page-block dark-record"><SectionHead no="05.3" eyebrow="BUILD FROM FIRST YEAR" title="Career preparation that does not depend on a claim">The placement cell becomes more useful when you arrive with basic, verifiable work. Build capability early and document it clearly.</SectionHead><Table head={["Route", "Practical move"]} rows={recruiterAndPreparation} /><External href="https://www.aecwb.edu.in/tp-officers.php">OPEN AEC TRAINING & PLACEMENT ROUTE</External></section></PageFrame>; }

export function FacultyPage() { return <PageFrame id="faculty"><section className="page-block"><SectionHead no="06.1" eyebrow="CONTACTING THE RIGHT DESK" title="Central and CSE support">A direct route is useful only if it is current. The public records below carry their route status so you know when a formal confirmation is wiser than an email guess.</SectionHead><RouteSummary title="People & support map" items={[["CENTRAL ROUTE", "OFFICIAL"], ["CSE DIRECTORY", "PUBLIC"], ["AEC DEPARTMENTS", "12"]]} /><div className="central-contact"><Landmark size={27} /><div><span>VERIFIED HIGH-PRIORITY ROUTE</span><h3>Asansol Engineering College</h3><p>Vivekananda Sarani, Kanyapur, Asansol – 713305</p></div><div><a href="tel:9073683912">9073683912</a><a href="mailto:principal@aecwb.edu.in">principal@aecwb.edu.in</a></div></div><Table head={["Function", "Named contact", "Route", "Status"]} rows={contacts} /></section><section className="page-block"><SectionHead no="06.2" eyebrow="CSE DESK" title="Public CSE faculty directory">Names, roles and displayed institutional emails are taken from the public CSE faculty page. Reconfirm the email address before sending sensitive personal or academic information.</SectionHead><Table head={["Faculty member", "Designation", "Displayed institutional email"]} rows={facultyRows} /><Evidence label="TECHNICAL SUPPORT">AEC’s public CSE technical-assistant page lists Suman Mallick (`suman.cse@aecwb.edu.in`) and Debendra Nath Pattanayak (`debendra.cse@aecwb.edu.in`) as senior technical assistants, with additional names on the source page.</Evidence></section><section className="page-block dark-record"><SectionHead no="06.3" eyebrow="WIDER AEC MAP" title="Departments and public academic routes" /><Table head={["Department", "Publicly named lead", "Route", "Context"]} rows={departmentDirectory.map(([department, lead, href, context]) => [department, lead, href, context])} /></section></PageFrame>; }

export function SocialPage() { return <PageFrame id="social"><section className="page-block"><SectionHead no="07.1" eyebrow="INSTITUTIONAL SIGNALS" title="Official social register">These first accounts are linked from the AEC public-site footer. YouTube channels are included as search-verified candidates only because the inspected footer did not link a canonical channel.</SectionHead><div className="signal-list">{socials.map(([title, href, tag, note]) => <LinkRow key={title} title={title} href={href} tag={tag} note={note} />)}</div></section><section className="page-block dark-record"><SectionHead no="07.2" eyebrow="COMMUNITY SIGNALS" title="Clubs, events and student communities">These pages can be useful for workshops, peer learning and opportunities. They are not silently treated as central institutional accounts.</SectionHead><div className="signal-list">{communities.map(([title, href, tag, note]) => <LinkRow key={title} title={title} href={href} tag={tag} note={note} />)}</div><Evidence label="FOLLOWING RULE">Before registering or paying for an event, confirm the organiser, venue, date, eligibility and payment route through the owner’s current post or a faculty/college confirmation.</Evidence></section></PageFrame>; }

export function ExtrasPage() { return <PageFrame id="extras"><section className="page-block"><SectionHead no="08.1" eyebrow="PAYMENTS & STAY" title="Campus reference—keep the caution attached">No public reference table should be treated as a current payment instruction. The panels below preserve what was found and what was not verified.</SectionHead><div className="extras-grid">{extraPanels.map(([title, figure, detail]) => <article key={title}><span>{title}</span><h3>{figure}</h3><p>{detail}</p></article>)}</div><div className="fee-strip"><span>CSE FEE REFERENCE / WBJEEB-HOSTED AEC-SUPPLIED PROFILE</span><div>{feeRows.map(([sem, amount]) => <p key={sem}><b>{sem}</b><span>{amount}</span></p>)}</div></div></section><section className="page-block"><SectionHead no="08.2" eyebrow="SAFEGUARDS & SUPPORT" title="Rules, scholarships and official forms">AEC navigation exposes scholarship, conduct, library rules, hostel rules, academic regulation, grievance redressal and anti-ragging routes. Use the live page for details rather than an old paraphrase.</SectionHead><div className="signal-list">{safeguardLinks.map(([title, href, note]) => <LinkRow key={title} title={title} href={href} tag="Official" note={note} />)}</div><Evidence label="SCHOLARSHIP NOTE">The public AEC overview confirms support for scholarship applications, but the retrieved overview did not publish current award amounts or full eligibility. Verify the active scheme before applying.</Evidence></section><section className="page-block dark-record"><SectionHead no="08.3" eyebrow="STUDENT-LIFE ROUTES" title="Community, alumni and what remains unverified">AEC’s annual-events route, department pages and club links provide the safer starting point for activities. The official alumni page states the association is registered, but its activities section had a public database-access error when reviewed. No extractable public transport schedule or sports page details were found in targeted checks.</SectionHead><div className="two-column-notes"><p><BookOpen size={18} /><span><b>Useful first-year pattern</b> Attend induction, identify a club or chapter that matches your genuine interest, and keep one hour weekly for a practical build or learning log.</span></p><p><ShieldAlert size={18} /><span><b>When a route is unclear</b> Ask a department office, library desk, admissions/college office or named institutional contact. Do not invent a form, deadline, warden contact or transport fee.</span></p></div></section></PageFrame>; }
