/** Curriculum Terminal: offset technical folio; graphite ground, Route Yellow verification, editorial data bands. */
import { useEffect, useState, type ReactNode } from "react";
import { AlertTriangle, ArrowDown, ArrowUpRight, Check, ChevronRight, Clipboard, Landmark, Menu, ShieldCheck, X } from "lucide-react";
import { assets, calendarRows, contactRows, facultyRows, feeRows, navItems, placementRows, quickLinks, references, semOne, semTwo, socialRows } from "@/data/guideData";

function Out({ href, children }: { href: string; children: ReactNode }) { return <a className="out" href={href} target="_blank" rel="noreferrer">{children}<ArrowUpRight size={13} /></a>; }
function DataTable({ head, rows }: { head: string[]; rows: readonly (readonly string[])[] }) { return <div className="table-scroll"><table><thead><tr>{head.map(x => <th key={x}>{x}</th>)}</tr></thead><tbody>{rows.map((r, i) => <tr key={`${r[0]}${i}`}>{r.map((c, j) => <td key={`${c}${j}`}>{c}</td>)}</tr>)}</tbody></table></div>; }
function Heading({ no, tag, title, children }: { no: string; tag: string; title: string; children: ReactNode }) { return <div className="section-lead"><span className="section-no">{no}</span><div><p className="kicker">{tag}</p><h2>{title}</h2><p>{children}</p></div></div>; }

export default function Home() {
  const [active, setActive] = useState("start"); const [menuOpen, setMenuOpen] = useState(false); const [copied, setCopied] = useState(false);
  useEffect(() => { const observer = new IntersectionObserver(entries => entries.forEach(e => { if (e.isIntersecting) setActive(e.target.id); }), { rootMargin: "-16% 0px -68%" }); navItems.forEach(([, id]) => { const el = document.getElementById(id); if (el) observer.observe(el); }); return () => observer.disconnect(); }, []);
  const jump = (id: string) => { document.getElementById(id)?.scrollIntoView({ behavior: "smooth", block: "start" }); setMenuOpen(false); };
  const copy = async () => { try { await navigator.clipboard.writeText("9073683912 · principal@aecwb.edu.in"); setCopied(true); window.setTimeout(() => setCopied(false), 1600); } catch { setCopied(false); } };
  return <div className="guide-shell">
    <header className="topbar"><a className="brand" href="#start" onClick={e => { e.preventDefault(); jump("start"); }}><img src={assets.mark} alt="AEC CSE route marker"/><span>AEC<b>//</b>CSE</span><small>field guide</small></a><div className="topbar-status"><i/> cited & dated <span>27 AUG 2026 · IST</span></div><button className="menu-btn" onClick={() => setMenuOpen(!menuOpen)} aria-label="Open guide index" aria-expanded={menuOpen}>{menuOpen ? <X size={19}/> : <Menu size={19}/>} INDEX</button></header>
    <aside className="rail"><div className="rail-label"><span>DOCUMENT INDEX</span><span>v1.0</span></div><nav>{navItems.map(([no, id, name]) => <button className={active === id ? "active" : ""} onClick={() => jump(id)} key={id}><i>{no}</i>{name}</button>)}</nav><div className="rail-note"><span>STATUS</span><strong><ShieldCheck size={15}/> cited & dated</strong><p>Verify anything that affects a deadline, payment or formal request.</p></div></aside>
    <div className={`mobile-index ${menuOpen ? "open" : ""}`}>{navItems.map(([no, id, name]) => <button onClick={() => jump(id)} key={id}><i>{no}</i>{name}<ChevronRight size={16}/></button>)}</div>
    <main className="document">
      <section id="start" className="hero"><div className="hero-img" style={{ backgroundImage: `url(${assets.hero})` }}/><div className="hero-content"><div className="hero-meta"><span>FIRST-YEAR B.TECH CSE</span><span>ASANSOL ENGINEERING COLLEGE</span></div><p className="kicker">PERSONAL / OFFLINE REFERENCE</p><h1>Find the official route<br/><em>before</em> the deadline finds you.</h1><div className="hero-foot"><p>An evidenced field manual for the links, people, first-year course structure and time-sensitive notices a new AEC CSE student needs most.</p><button onClick={() => jump("curriculum")}>START AT THE CURRICULUM <ArrowDown size={16}/></button></div></div></section>
      <section className="guide-section">
        <Heading no="01" tag="FIRST ACTION" title="Fast route: official links & portals">AEC identifies itself as established in 1998, AICTE-approved, MAKAUT-affiliated and UGC 2(f)-recognised. Use AEC for college-specific information, MAKAUT Exam for university examination notices, and the current MAKAUT NEP index for curriculum. <sup>[01] [02] [03]</sup></Heading>
        <div className="warning"><AlertTriangle size={18}/><p><strong>Do not use a random “ERP” link forwarded in a chat group.</strong> AEC’s public navigation shows “Student Login,” but no stable official ERP URL was verified. Ask during induction or route through the AEC central contact. Never share passwords, OTPs, registration numbers or fee-payment credentials through a third-party form.</p></div>
        <div className="route-list">{quickLinks.map(([name, href, access, note]) => <Out href={href} key={name}><span className="access">{access}</span><div><h3>{name}</h3><p>{note}</p></div></Out>)}</div>
      </section>
      <section id="curriculum" className="guide-section">
        <Heading no="02" tag="ACADEMIC MAP" title="First-year CSE curriculum">MAKAUT’s current NEP index lists <strong>B.Tech CSE, Course Code 001</strong>, effective from AY 2026–27 and last updated 21 August 2026. Its linked PDFs explicitly call first-year common across B.Tech programmes and put CSE in Group A. <sup>[06] [09] [10]</sup></Heading>
        <div className="batch-note"><div><span>IMPORTANT BATCH CHECK</span><h3>“R25” is not automatically the same thing as the AY 2026–27 document.</h3></div><p>If you entered in another academic session, confirm the applicable batch document with AEC before treating a course code, credit count or calendar date as binding.</p></div>
        <div className="sem-head"><div><span>SEMESTER I</span><h3>20 credits</h3><p>Physics, Physics Lab, Engineering Graphics & Design and Indian Constitution sit with CSE/allied Group A.</p></div><Out href="https://makautexam.net/aicte_details/Syllabusnep/sem126.pdf">Open official Sem I PDF</Out></div><DataTable head={["Code", "Course", "L–T–P", "Credits", "Note"]} rows={semOne}/><p className="check"><Check size={17}/>Mandatory, non-credit: a three-week Induction Programme with Universal Human Values precedes Semester I. <sup>[09]</sup></p>
        <div className="sem-head second"><div><span>SEMESTER II</span><h3>24 credits</h3><p>CSE/allied Group A rotates to Chemistry, Chemistry Lab, Workshop Practice and Indian Knowledge System.</p></div><Out href="https://makautexam.net/aicte_details/Syllabusnep/sem226.pdf">Open official Sem II PDF</Out></div><DataTable head={["Code", "Course", "L–T–P", "Credits", "Note"]} rows={semTwo}/>
        <div className="two-notes"><p><strong>Optional exit:</strong> 28 credits apply only for the UG Certificate exit path, which additionally requires 4 work-based vocational / summer internship / apprenticeship credits. <sup>[10]</sup></p><p><strong>What is not public yet:</strong> the current official index showed no CSE documents for Semesters III–VIII on the research date. Do not silently substitute an older archive. <sup>[06]</sup></p></div>
      </section>
      <section className="signal"><div className="signal-img" style={{ backgroundImage: `url(${assets.circuit})` }}/><div className="signal-copy"><p className="kicker">KEY CSE ENTRY COURSE · 26-ES-CS201</p><h2>Programming for Problem Solving <em>and</em> Introduction to AI</h2><p>This Semester II course assumes no prior programming. The official map moves from computer basics and algorithms through C, functions, pointers, files, search/sort and basic algorithm efficiency—then closes with AI concepts, agents and applications.</p><div><span>ASSESSMENT</span><strong>CA 30 + ESE 70</strong><p>At least half of Groups B and C involve writing or reading C code; one Group C question covers AI. <sup>[10]</sup></p></div></div></section>
      <section id="calendar" className="guide-section">
        <Heading no="03" tag="TIME-SENSITIVE" title="Calendar, assessment & exam checkpoints">The MAKAUT Academic Calendar is explicitly <strong>provisional</strong>. Its latest official notice overrides this static reference. Keep the routine, AEC circular and fee/form-fill-up acknowledgement together. <sup>[03] [14]</sup></Heading><DataTable head={["Period", "Odd semester 2026–27", "Even semester 2026–27"]} rows={calendarRows}/><div className="action-strip"><span>PRESSURE-PROOF ROUTINE</span><p>01. Save every CA date once AEC publishes its internal schedule. <i/> 02. Monitor attendance well before the eligibility-upload window. <i/> 03. Capture the official notice that changes your deadline.</p></div>
      </section>
      <section id="library" className="guide-section">
        <Heading no="04" tag="STUDY INFRASTRUCTURE" title="Library, e-resources & skills routes">AEC’s Library page advertises computing titles including <em>Cloud Computing</em>, <em>Practical Statistics for Data Scientists</em>, <em>Compilers: Principles, Techniques & Tools</em> and <em>Computer System Architecture</em>. It exposes book/e-copy requisition forms and provides the OPAC workflow. <sup>[04]</sup></Heading>
        <div className="library-grid"><div className="opac"><span>WEB OPAC WORKFLOW</span><ol><li>Obtain your AEC username and password.</li><li>Log in to Web OPAC.</li><li>Choose title, author or subject.</li><li>Search, then record item details.</li></ol><Out href="http://122.252.249.26:5096/forms/frmLogin.aspx">Open AEC Web OPAC</Out></div><div className="resource"><article><span>KNIMBUS</span><h3>Account-gated digital library</h3><p>Public access does not show specific e-books, journals, past papers or databases. Confirm what your account includes directly with the library.</p></article><article><span>MOOC CREDIT</span><h3>Integrated into both semesters</h3><p>MOOCs / Skills appear as official skill-enhancement courses in Sem I and II. Confirm current approved course and submission procedure with AEC first.</p></article><article><span>NPTEL / SWAYAM</span><h3>Use the syllabus as your filter</h3><p>MAKAUT links NPTEL and SWAYAM as academic resources; the course PDF suggests C programming, calculus and AI routes. <sup>[02] [10]</sup></p></article></div></div>
      </section>
      <section id="placements" className="guide-section">
        <Heading no="05" tag="READ THE FOOTNOTE" title="Placement record: published figures & conflicts">AEC’s homepage and Shiksha align on a 2023 aggregate summary of ₹22 LPA highest and ₹4.92 LPA average, with 500+ offers and 250+ recruiters reported by Shiksha. Another AEC-submitted profile hosted by WBJEEB gives different maximum CTC figures. <sup>[01] [15] [16]</sup></Heading><div className="conflict"><span><AlertTriangle size={19}/> FIGURE CONFLICT</span><p>For 2023, the WBJEEB-hosted AEC-submitted profile says <strong>₹23 LPA</strong>; AEC’s homepage and Shiksha say <strong>₹22 LPA</strong>. This guide does not choose a number. Quote the reporting basis and re-check the newest official placement report.</p></div><DataTable head={["Year / basis", "Placed", "Highest CTC", "Average / median", "Evidence & caution"]} rows={placementRows}/><p className="minor">AEC’s direct “Placement Report — 2025 Batch” PDF was not independently readable in this research because the source presented a certificate error / anti-bot page. Search snippets showed a branch table, but it is not reproduced here. <sup>[17]</sup></p>
      </section>
      <section id="contacts" className="guide-section">
        <Heading no="06" tag="WHO TO CONTACT" title="Contact directory: verified public routes">Use the college’s central route when a department page does not display a dedicated official contact. Individual titles can change; source status is included so you know what is current, missing or inconsistent.</Heading><div className="central"><div><span>OFFICIAL CENTRAL ROUTE</span><h3>Asansol Engineering College</h3><p>Vivekananda Sarani, Kanyapur, Asansol – 713305</p></div><div><a href="tel:9073683912">9073683912</a><a href="mailto:principal@aecwb.edu.in">principal@aecwb.edu.in</a></div><button onClick={copy}>{copied ? <Check size={16}/> : <Clipboard size={16}/>} {copied ? "COPIED" : "COPY"}</button></div><DataTable head={["Function", "Named contact", "Public route", "Status"]} rows={contactRows}/>
      </section>
      <section id="faculty" className="guide-section">
        <Heading no="07" tag="CSE DESK" title="CSE faculty directory">The CSE faculty page displays these institutional routes. Several page `mailto:` targets conflict with the visually written email; the table uses the displayed text. Reconfirm the address before a formal or sensitive message. <sup>[19]</sup></Heading><DataTable head={["Faculty member", "Designation", "Institutional email as displayed"]} rows={facultyRows}/><p className="minor">For laboratory matters, the technical-assistant page lists Suman Mallick (`suman.cse@aecwb.edu.in`) and Debendra Nath Pattanayak (`debendra.cse@aecwb.edu.in`) as senior technical assistants; additional names are on the source page. <sup>[24]</sup></p>
      </section>
      <section id="campus" className="guide-section">
        <Heading no="08" tag="PAYMENTS & STAY" title="Fees, hostel & practical campus reference">The detailed sem-wise CSE fee schedule found was an AEC-submitted profile hosted by WBJEEB; the document says its information is not independently verified by WBJEEB. It is a reference—not a demand notice. Confirm the current semester amount and payment procedure with AEC. <sup>[16]</sup></Heading><div className="campus-grid"><div className="fee"><span>CSE FEE REFERENCE</span><strong>₹701,800</strong><p>Calculated eight-semester total from the listed figures.</p>{feeRows.map(([sem, amt]) => <div key={sem}><span>{sem}</span><b>{amt}</b></div>)}<div className="total"><span>8-semester calculated total</span><b>₹701,800</b></div></div><div className="hostel"><Landmark size={29}/><p className="kicker">HOSTEL REFERENCE</p><h3>600 boys’ + 400 girls’ seats listed.</h3><p>The AEC-submitted profile gives those seat counts. AEC’s homepage separately describes three boys’ and two girls’ hostels, with AC/non-AC rooms for about 1,000 students. No dedicated hostel phone/email was verified; the Library page links the admission form. <sup>[01] [04] [16]</sup></p><Out href="https://www.aecwb.edu.in/library-home.php">Open hostel form route</Out></div></div><div className="action-strip"><span>FEE SCOPE CONFLICT</span><p>AEC’s homepage gives a broad B.Tech estimate of around ₹1.04 lakh/year and ₹3.25–6.1 lakh total. It does not reconcile with the detailed CSE schedule. Keep the difference visible and reconfirm before payment. <sup>[01] [16]</sup></p></div>
      </section>
      <section id="social" className="guide-section">
        <Heading no="09" tag="SIGNAL CHECK" title="Official social register">The first four accounts below are linked from AEC’s public-site footer. Two YouTube channels are search-verified candidates but were not linked there; use them cautiously until AEC confirms the canonical channel.</Heading><div className="social-list">{socialRows.map(([name, href, status, note]) => <Out href={href} key={name}><span>{status}</span><div><h3>{name}</h3><p>{note}</p></div></Out>)}</div>
      </section>
      <section id="sources" className="guide-section sources">
        <div className="source-banner" style={{ backgroundImage: `linear-gradient(90deg,rgba(14,17,19,.96),rgba(14,17,19,.52)),url(${assets.source})` }}><p className="kicker">CHECK THE SOURCE</p><h2>Last updated: 27 August 2026 · IST</h2><p>This document makes uncertainty explicit. If it affects attendance, academic record, fees, exam eligibility or formal communication, open the latest official notice before acting.</p></div><Heading no="10" tag="SOURCE REGISTER" title="References & reliability order">For academic or official action: use a current MAKAUT notice first, then a current AEC notice or department page, and only then a dated third-party cross-check. Login-gated links are never required to view this guide.</Heading><div className="reliability"><p><b>01 · Deadline?</b> MAKAUT Exam notice → AEC circular → screenshot only if the official URL is attached.</p><p><b>02 · Course code?</b> Current MAKAUT index and linked PDF → AEC department page.</p><p><b>03 · Fees?</b> AEC-issued demand / payment instruction → AEC central contact.</p><p><b>04 · Faculty?</b> Current department page + confirmation → central AEC contact.</p></div><div className="references">{references.map(([id, title, href]) => <Out href={href} key={id}><span>[{id}]</span><div><h3>{title}</h3><p>{href}</p></div></Out>)}</div>
      </section>
      <footer><div className="footer-brand"><img src={assets.mark} alt=""/>AEC<span>//</span>CSE</div><p>First-year survival guide · personal offline reference · research date 27 August 2026 (IST)</p><button onClick={() => jump("start")}>BACK TO TOP <ArrowUpRight size={14}/></button></footer>
    </main>
  </div>;
}
